version: '3'
services:
    postgresql:
        image: postgres:10.5
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: mlflow-db
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            restart: always
        ports:
            - 0.0.0.0:5432:5432
    waitfordb:
        image: dadarek/wait-for-dependencies
        depends_on:
            - postgresql
        command: postgresql:5432        
    mlflow-server:
        build: .
        ports:
            - 0.0.0.0:5000:5000
        environment:
            DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/mlflow-db
            MLFLOW_ARTIFACT_ROOT: "${MLFLOW_ARTIFACT_ROOT}"
            MLFLOW_TRACKING_USERNAME: "${MLFLOW_TRACKING_USERNAME}"
            MLFLOW_TRACKING_PASSWORD: "${MLFLOW_TRACKING_PASSWORD}"
        restart: always
        depends_on:
            - waitfordb
        volumes:
               - "${MLFLOW_ARTIFACT_ROOT}:${MLFLOW_ARTIFACT_ROOT}"
    mlflow-ui:
        build: .
        ports:
            - 0.0.0.0:80:80
        environment:
            DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/mlflow-db
            MLFLOW_TRACKING_USERNAME: "${MLFLOW_TRACKING_USERNAME}"
            MLFLOW_TRACKING_PASSWORD: "${MLFLOW_TRACKING_PASSWORD}"
            MLFLOW_ARTIFACT_ROOT: "${MLFLOW_ARTIFACT_ROOT}"
        restart: always
        depends_on:
            - mlflow-server
        entrypoint: ./start_ui.sh
        volumes:
                - "${MLFLOW_ARTIFACT_ROOT}:${MLFLOW_ARTIFACT_ROOT}"
